### ISSUE TITLE
Small fixes for little things

### ISSUE THREAD

**Issue by aryler** [pspjuth/DiffUtilTcl#2]
[patch-Makefile_in.txt](https://github.com/pspjuth/DiffUtilTcl/files/1537841/patch-Makefile_in.txt)
[patch-doc_diffutil_man.txt](https://github.com/pspjuth/DiffUtilTcl/files/1537842/patch-doc_diffutil_man.txt)

**Comment by pspjuth** [comment]
Why remove doc from phony?

**Comment by aryler** [comment]
'doc' shouldn't be phony since it has real dependencies

But this is a very pedantic nitpick.
In my tests it doesn't seem to make a difference if 'doc' is phony or not.
